INSERT INTO tblQuestions (title, level, marks, answer_id, topic_id, created_at, updated_at, created_by, updated_by)
VALUES
('When would you use encapsulation in Java?', 1, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What are the benefits of encapsulation?', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('How does inheritance work in Java?', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('Explain the concept of abstract class in Java.', 2, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What are the benefits of final keyword?', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What is final keyword in Java?', 1, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('Explain the concept of static block in Java.', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('Explain the concept of encapsulation in Java.', 2, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What are the benefits of polymorphism?', 1, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What is final keyword in Java?', 2, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('How does static block work in Java?', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What are the benefits of polymorphism?', 2, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('When would you use garbage collection in Java?', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('Explain the concept of garbage collection in Java.', 1, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('How does inheritance work in Java?', 2, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What is polymorphism in Java?', 1, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What are the benefits of JVM?', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('Explain the concept of static block in Java.', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What are the benefits of final keyword?', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('When would you use garbage collection in Java?', 1, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('Explain the concept of encapsulation in Java.', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('Explain the concept of garbage collection in Java.', 1, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What is garbage collection in Java?', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('Explain the concept of inheritance in Java.', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('Explain the concept of inheritance in Java.', 2, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('When would you use encapsulation in Java?', 2, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('How does static block work in Java?', 1, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('How does encapsulation work in Java?', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What is JVM in Java?', 2, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('Explain the concept of interface in Java.', 2, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What are the benefits of garbage collection?', 2, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What are the benefits of garbage collection?', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('Explain the concept of encapsulation in Java.', 1, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('When would you use garbage collection in Java?', 2, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('Explain the concept of final keyword in Java.', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('Explain the concept of final keyword in Java.', 2, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What are the benefits of interface?', 1, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What are the benefits of interface?', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('How does interface work in Java?', 2, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('How does final keyword work in Java?', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('Explain the concept of polymorphism in Java.', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What is static block in Java?', 1, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('Explain the concept of interface in Java.', 1, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('Explain the concept of multithreading in Java.', 2, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('How does abstract class work in Java?', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('When would you use interface in Java?', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What are the benefits of garbage collection?', 1, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('How does abstract class work in Java?', 2, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('What are the benefits of interface?', 1, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('When would you use interface in Java?', 3, 1, NULL, 1, CURRENT_TIMESTAMP, NULL, 11, NULL),
('Define schema in SQL.', 3, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('What is the difference between foreign key and its alternative?', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Define JOIN in SQL.', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Why is view important in DBMS?', 2, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('What is the difference between index and its alternative?', 3, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Give an example of JOIN in a relational schema.', 2, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('What is the difference between schema and its alternative?', 2, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Give an example of view in a relational schema.', 3, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Define primary key in SQL.', 2, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('What is the difference between transaction and its alternative?', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Define transaction in SQL.', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Give an example of subquery in a relational schema.', 2, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Why is normalization important in DBMS?', 3, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Why is foreign key important in DBMS?', 2, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Give an example of transaction in a relational schema.', 2, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('What is the difference between schema and its alternative?', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Explain the role of primary key in databases.', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Explain the role of normalization in databases.', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Explain the role of foreign key in databases.', 3, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Explain the role of schema in databases.', 3, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Explain the role of transaction in databases.', 2, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Define normalization in SQL.', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Define view in SQL.', 3, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Define primary key in SQL.', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Why is transaction important in DBMS?', 2, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Give an example of transaction in a relational schema.', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Define transaction in SQL.', 3, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Give an example of primary key in a relational schema.', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Explain the role of normalization in databases.', 2, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Explain the role of normalization in databases.', 2, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('What is the difference between view and its alternative?', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Give an example of subquery in a relational schema.', 3, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('What is the difference between primary key and its alternative?', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Define JOIN in SQL.', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('What is the difference between ACID and its alternative?', 2, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Explain the role of subquery in databases.', 2, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('What is the difference between index and its alternative?', 3, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('What is the difference between index and its alternative?', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Define index in SQL.', 3, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('What is the difference between ACID and its alternative?', 3, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Define index in SQL.', 3, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Explain the role of ACID in databases.', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Define ACID in SQL.', 2, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Define primary key in SQL.', 2, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('What is the difference between primary key and its alternative?', 3, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Explain the role of JOIN in databases.', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Why is primary key important in DBMS?', 1, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Explain the role of index in databases.', 3, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Explain the role of transaction in databases.', 2, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('Explain the role of normalization in databases.', 3, 1, NULL, 2, CURRENT_TIMESTAMP, NULL, 12, NULL),
('When is searching more efficient?', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('When is stack more efficient?', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('How is binary tree implemented?', 3, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('How is hash table implemented?', 3, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('Explain the use of graph in real-world applications.', 3, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('How is sorting implemented?', 3, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('How is graph implemented?', 3, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('When is hash table more efficient?', 2, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('When is searching more efficient?', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('When is hash table more efficient?', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('Compare binary tree with other structures.', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('Explain the use of array in real-world applications.', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('Compare hash table with other structures.', 2, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('When is heap more efficient?', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('Explain the use of searching in real-world applications.', 3, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('What is a binary tree in data structures?', 3, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('When is stack more efficient?', 3, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('Compare binary tree with other structures.', 2, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('How is graph implemented?', 2, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('Compare sorting with other structures.', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('Explain the use of queue in real-world applications.', 3, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('Compare binary tree with other structures.', 3, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('How is graph implemented?', 2, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('When is sorting more efficient?', 2, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('When is stack more efficient?', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('How is sorting implemented?', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('What is a binary tree in data structures?', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('Compare hash table with other structures.', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('How is queue implemented?', 2, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('What is a sorting in data structures?', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('When is binary tree more efficient?', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('Explain the use of queue in real-world applications.', 2, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('When is graph more efficient?', 2, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('What is a queue in data structures?', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('When is hash table more efficient?', 2, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('How is stack implemented?', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('Compare sorting with other structures.', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('When is queue more efficient?', 2, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('When is graph more efficient?', 3, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('What is a heap in data structures?', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('Explain the use of linked list in real-world applications.', 2, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('Explain the use of stack in real-world applications.', 3, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('Compare binary tree with other structures.', 3, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('What is a graph in data structures?', 2, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('When is binary tree more efficient?', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('Compare queue with other structures.', 3, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('When is graph more efficient?', 2, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('How is heap implemented?', 2, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('When is sorting more efficient?', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('Compare heap with other structures.', 1, 1, NULL, 3, CURRENT_TIMESTAMP, NULL, 13, NULL),
('When is system call triggered in OS?', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('When is process triggered in OS?', 1, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('Describe file system in an operating system.', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('What is the purpose of segmentation?', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('Describe system call in an operating system.', 1, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('What is the purpose of system call?', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('Explain interrupt with an example.', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('What is the purpose of file system?', 1, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('How does system call affect system performance?', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('What is the purpose of system call?', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('What is the purpose of memory management?', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('When is system call triggered in OS?', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('When is thread triggered in OS?', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('When is scheduling triggered in OS?', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('When is segmentation triggered in OS?', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('How does paging affect system performance?', 1, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('When is deadlock triggered in OS?', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('What is the purpose of interrupt?', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('What is the purpose of segmentation?', 1, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('How does memory management affect system performance?', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('How does memory management affect system performance?', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('What is the purpose of memory management?', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('When is deadlock triggered in OS?', 1, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('How does paging affect system performance?', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('Describe process in an operating system.', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('When is scheduling triggered in OS?', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('Explain segmentation with an example.', 1, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('What is the purpose of deadlock?', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('How does scheduling affect system performance?', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('How does memory management affect system performance?', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('Describe file system in an operating system.', 1, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('Describe interrupt in an operating system.', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('When is thread triggered in OS?', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('How does file system affect system performance?', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('Describe file system in an operating system.', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('Explain deadlock with an example.', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('How does memory management affect system performance?', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('Describe interrupt in an operating system.', 1, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('What is the purpose of deadlock?', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('When is deadlock triggered in OS?', 1, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('When is paging triggered in OS?', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('How does thread affect system performance?', 1, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('Describe scheduling in an operating system.', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('Explain paging with an example.', 1, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('When is system call triggered in OS?', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('When is segmentation triggered in OS?', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('What is the purpose of memory management?', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('How does scheduling affect system performance?', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('What is the purpose of thread?', 2, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('Explain scheduling with an example.', 3, 1, NULL, 4, CURRENT_TIMESTAMP, NULL, 14, NULL),
('Explain responsive design in context of modern web design.', 2, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('What is the role of HTML in web development?', 2, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How is API used in front-end?', 3, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How is JavaScript used in front-end?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How is DOM used in front-end?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How can accessibility improve UX?', 3, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('Explain DOM in context of modern web design.', 3, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('Why do developers use CSS?', 3, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How is local storage used in front-end?', 3, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('Explain CSS in context of modern web design.', 2, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How is React used in front-end?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('Explain accessibility in context of modern web design.', 2, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How is CSS used in front-end?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('Why do developers use responsive design?', 3, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How can API improve UX?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How can local storage improve UX?', 3, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How is CSS used in front-end?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('Why do developers use HTML?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How can responsive design improve UX?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How can local storage improve UX?', 2, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('What is the role of local storage in web development?', 2, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How can React improve UX?', 3, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How can JavaScript improve UX?', 2, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('Explain local storage in context of modern web design.', 3, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('What is the role of AJAX in web development?', 3, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How can local storage improve UX?', 2, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('Explain accessibility in context of modern web design.', 2, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How is accessibility used in front-end?', 2, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How can React improve UX?', 3, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('What is the role of CSS in web development?', 3, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('Why do developers use API?', 2, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('Why do developers use CSS?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('What is the role of React in web development?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('What is the role of React in web development?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How can API improve UX?', 3, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('Explain HTML in context of modern web design.', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('Explain accessibility in context of modern web design.', 3, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How can DOM improve UX?', 3, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('What is the role of CSS in web development?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('Explain accessibility in context of modern web design.', 2, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How can API improve UX?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How is HTML used in front-end?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How is HTML used in front-end?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('Explain CSS in context of modern web design.', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('What is the role of API in web development?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('What is the role of AJAX in web development?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How is local storage used in front-end?', 1, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How can local storage improve UX?', 2, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('What is the role of accessibility in web development?', 3, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL),
('How can DOM improve UX?', 2, 1, NULL, 5, CURRENT_TIMESTAMP, NULL, 15, NULL);
